//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexcoWeb.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budget()
        {
            this.Expenditures = new HashSet<Expenditure>();
            this.Expenditures1 = new HashSet<Expenditure>();
            this.Incomes = new HashSet<Income>();
            this.Incomes1 = new HashSet<Income>();
        }
    
        public int BudgetId { get; set; }
        public string DescriptionBudget { get; set; }
        public Nullable<int> TotalIncome { get; set; }
        public Nullable<int> TotalExpense { get; set; }
        public System.DateTime BudgetAddedOn { get; set; }
        public Nullable<int> TotalBudget { get; set; }
        public Nullable<int> Expenditure_ExpenditureId { get; set; }
        public Nullable<int> Expenditure_ExpenditureId1 { get; set; }
        public Nullable<int> Income_IncomeId { get; set; }
        public Nullable<int> Income_IncomeId1 { get; set; }
    
        public virtual Expenditure Expenditure { get; set; }
        public virtual Expenditure Expenditure1 { get; set; }
        public virtual Income Income { get; set; }
        public virtual Income Income1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditure> Expenditures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditure> Expenditures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Income> Incomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Income> Incomes1 { get; set; }
    }
}
