//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexcoWeb.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expenditure()
        {
            this.Budgets = new HashSet<Budget>();
            this.Budgets1 = new HashSet<Budget>();
        }
    
        public int ExpenditureId { get; set; }
        public Nullable<int> Travel { get; set; }
        public Nullable<int> Food { get; set; }
        public Nullable<int> Entertaiment { get; set; }
        public Nullable<int> Auto { get; set; }
        public Nullable<int> HouseholdExpenses { get; set; }
        public Nullable<int> Clothing { get; set; }
        public Nullable<int> Loan { get; set; }
        public Nullable<int> OtherExpenses { get; set; }
        public string DescriptionExpenditure { get; set; }
        public System.DateTime ExpensesAddedOn { get; set; }
        public Nullable<int> TotalExpense { get; set; }
        public Nullable<int> Budget_BudgetId { get; set; }
        public Nullable<int> Budget_BudgetId1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budgets1 { get; set; }
        public virtual Budget Budget { get; set; }
        public virtual Budget Budget1 { get; set; }
    }
}
